# Generated by Django 4.2.2 on 2023-07-04 04:17

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                default="avatar.svg",
                upload_to="images/user_profile_picture",
                validators=[
                    accounts.validators.validate_image_size,
                    django.core.validators.validate_image_file_extension,
                ],
            ),
        ),
    ]
