# Generated by Django 4.2.2 on 2023-07-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(name="customuser", managers=[],),
        migrations.AlterField(
            model_name="customuser",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Backend Developer", "Backend Developer"),
                    ("Frontend Developer", "Frontend Developer"),
                    ("Mobile Developer", "Mobile Developer"),
                    ("Product Manager", "Product Manager"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
