# Generated by Django 4.2.2 on 2023-07-08 21:37

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
    ]
