# Generated by Django 4.2.2 on 2023-07-11 14:14

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.FileField(
                blank=True,
                default="pi.png",
                null=True,
                upload_to="images/user_profile_picture",
                validators=[
                    accounts.validators.validate_image_size,
                    django.core.validators.validate_image_file_extension,
                ],
            ),
        ),
    ]
