# Generated by Django 4.2.2 on 2023-07-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_managers_alter_customuser_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_superadmin",
            field=models.BooleanField(default=False),
        ),
    ]
