# Generated by Django 4.2.2 on 2023-07-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_is_admin_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(default=True),
        ),
    ]
