# Generated by Django 4.2.2 on 2023-07-04 10:50

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                default="pi.png",
                upload_to="images/user_profile_picture",
                validators=[
                    accounts.validators.validate_image_size,
                    django.core.validators.validate_image_file_extension,
                ],
            ),
        ),
    ]
