# Generated by Django 4.2.2 on 2023-07-06 03:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_alter_customuser_options_alter_customuser_is_admin_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(
                null=True, validators=[accounts.models.validate_date_of_birth]
            ),
        ),
    ]
