# Generated by Django 4.2.2 on 2023-07-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(model_name="customuser", name="permission_level",),
        migrations.AddField(
            model_name="customuser",
            name="permission_level",
            field=models.ManyToManyField(to="accounts.permissionlevel"),
        ),
    ]
