# Generated by Django 4.2.2 on 2023-07-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0007_permissionlevel_remove_customuser_permission_level_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser", options={"ordering": ["-date_joined"]},
        ),
    ]
