# Generated by Django 4.2.2 on 2023-07-12 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication", name="is_invited_for_assessment",
        ),
    ]
