# Generated by Django 4.2.2 on 2023-07-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(
                choices=[("Lagos", "Lagos"), ("Abuja", "Abuja"), ("Ibadan", "Ibadan")],
                default="Lagos",
                max_length=100,
            ),
        ),
    ]
