# Generated by Django 4.2.2 on 2023-07-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_job_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(model_name="job", name="location",),
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.ManyToManyField(
                related_name="job_locations", to="job.location"
            ),
        ),
    ]
