# Generated by Django 4.2.2 on 2023-07-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_remove_jobapplication_is_invited_for_assessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="is_invited_for_assessment",
            field=models.BooleanField(default=False),
        ),
    ]
