# Generated by Django 4.2.2 on 2023-07-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_jobapplication_is_invited_for_assessment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="jobapplication", options={"ordering": ["-applied_at"]},
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["role", "job_type"], name="job_job_role_602845_idx"
            ),
        ),
    ]
