# Generated by Django 4.2.2 on 2023-07-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_alter_job_options_alter_jobapplication_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewinvitation",
            name="is_not_draft",
            field=models.BooleanField(default=True),
        ),
    ]
