# Generated by Django 4.2.2 on 2023-07-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0005_interviewinvitation_is_not_draft"),
    ]

    operations = [
        migrations.RemoveField(model_name="jobapplication", name="job",),
        migrations.AddField(
            model_name="jobapplication",
            name="job",
            field=models.ManyToManyField(related_name="applications", to="job.job"),
        ),
    ]
